// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuerySplittingExample.Data;

#nullable disable

namespace QuerySplittingExample.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221108135816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuerySplittingExample.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfRegistration = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(743),
                            FirstName = "Mike",
                            LastName = "Miers"
                        },
                        new
                        {
                            Id = 2,
                            DateOfRegistration = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(746),
                            FirstName = "Alex",
                            LastName = "Spax"
                        },
                        new
                        {
                            Id = 3,
                            DateOfRegistration = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(748),
                            FirstName = "Bob",
                            LastName = "Marley"
                        },
                        new
                        {
                            Id = 4,
                            DateOfRegistration = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(750),
                            FirstName = "Ana",
                            LastName = "Mikela"
                        },
                        new
                        {
                            Id = 5,
                            DateOfRegistration = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(751),
                            FirstName = "Maria",
                            LastName = "Janovsky"
                        });
                });

            modelBuilder.Entity("QuerySplittingExample.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(591),
                            Name = "Data Engineering"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(624),
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(626),
                            Name = "Social Engineering"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(627),
                            Name = "NLP"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(629),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(631),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(633),
                            Name = "Data Mining"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(634),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            DateAdded = new DateTime(2022, 11, 8, 15, 58, 15, 972, DateTimeKind.Local).AddTicks(636),
                            Name = "Mobile Development"
                        });
                });

            modelBuilder.Entity("QuerySplittingExample.Data.Entities.Course", b =>
                {
                    b.HasOne("QuerySplittingExample.Data.Entities.Author", null)
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuerySplittingExample.Data.Entities.Author", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
